earthquake:
  min_magnitude: 6.0
  max_depth_km: 700

weather:
  include_events:
    - Flood Warning
    - Coastal Flood Warning
    - Flash Flood Warning
    - Lakeshore Flood Warning
    - Hurricane Warning
    - Hurricane Force Wind Warning
    - Storm Warning
    - Winter Storm Warning
    - Dust Storm Warning
    - Ice Storm Warning
    - Tropical Storm Warning
    - Severe Thunderstorm Warning
  exclude_events:
    - Special Weather Statement
    # - Hazardous Weather Outlook
